#!/bin/bash

Echo "Running transcriber"
source venv/bin/activate

YOUTUBE_URL="https://www.youtube.com/live/k6RLAsTeIJc?si=5ptd8zYmqjei1Oj1"
FILE_NAME="TN_Vazroditelen_Proteses"
METHOD="fast_whisper"
TASK="translate"

# Enable debugging to echo each command
set -x
venv/bin/python transcribe_youtube.py \
    --youtube_url "$YOUTUBE_URL" \
    --file_name "$FILE_NAME" \
    --method "$METHOD" \
    --task "$TASK"
# Disable debugging
set +x

# cp output/trikvartiri.srt ../srt_translate/input/trikvartiri.srt

#   --youtube_url YOUTUBE_URL
#                         URL of the YouTube video to transcribe
#   --file_name FILE_NAME
#                         Base name for the downloaded audio file
#   --method {whisper,fast_whisper,whisper_lib}
#                         Transcription method to use: 'whisper', 'fast_whisper', or 'whisper_lib'
#   --task {transcribe,translate,run_main}
#                         Task for fast_whisper method: 'transcribe' or 'translate'