#!/bin/bash

Echo "Running transcriber script - downloading audio from YouTube and transcribing it."
Echo "First login to youtube in your browser if you haven't done so."

source venv/bin/activate

YOUTUBE_URL="https://www.youtube.com/watch?v=yk-4mH22EzU&list=PL-CsGB9XKEpRuPPrUplJzrlQ9f5O8bxz7"
FILE_NAME="Moskva_stiska_zibi"
METHOD="fast_whisper"
TASK="translate"

# Enable debugging to echo each command
set -x
venv/bin/python transcribe_youtube.py \
    --youtube_url "$YOUTUBE_URL" \
    --file_name "$FILE_NAME" \
    --method "$METHOD" \
    --task "$TASK"
# Disable debugging
set +x

# cp output/trikvartiri.srt ../srt_translate/input/trikvartiri.srt

#   --youtube_url YOUTUBE_URL
#                         URL of the YouTube video to transcribe
#   --file_name FILE_NAME
#                         Base name for the downloaded audio file
#   --method {whisper,fast_whisper,whisper_lib}
#                         Transcription method to use: 'whisper', 'fast_whisper', or 'whisper_lib'
#   --task {transcribe,translate,run_main}
#                         Task for fast_whisper method: 'transcribe' or 'translate'